@Survive.Api_HostAddress = http://localhost:5176
@ACCESS_JWT=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjQ3MWM4ZmQ3LTVjNmItNGUyMS1iOWM5LWU2YjNiMjhmNjE3NCIsInN1YiI6ImFkbWluIiwiZW1haWwiOiJhZG1pbiIsImp0aSI6ImE4M2M5MmE1LTgzZTUtNDllOC1hMDNmLTlhMDMyOTdhMjA0NiIsIm5iZiI6MTcwNzY4Mjc1OSwiZXhwIjoxNzA3NjgzMDU5LCJpYXQiOjE3MDc2ODI3NTksImlzcyI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyIsImF1ZCI6Imh0dHBzOi8vam95ZGlwa2FuamlsYWwuY29tLyJ9.yxAaNxOFUzEVuWcuyesEn5dpSwu_3RxybuJV1mXy2Xyp9XMcLcd9oFrrdtDbAs37FdiIxv-PfZhDCGxypO3Bmw
@security=security

GET {{Survive.Api_HostAddress}}/{{security}}/getMessage
Accept: application/json
Authorization: Bearer {{ACCESS_JWT}}
###

POST {{Survive.Api_HostAddress}}/{{security}}/createToken
Content-Type: application/json

{
  "userName": "admin",
  "password": "admin"
}
###

POST {{Survive.Api_HostAddress}}/product/
Content-Type: application/json
Authorization: Bearer {{ACCESS_JWT}}

{
  "name": "admin",
  "description": "admin"
}